### ISSUE TITLE
Use async_std::fs instead of std::fs?

### ISSUE THREAD

**Issue by anatawa12** [deepu105/concurrency-benchmarks#3]
It looks this is using std::fs, synchronous filesystem API from the standard library. 

https://github.com/deepu105/concurrency-benchmarks/blob/39b7d5cd3ab7b105b293cf07420c7eb94dcccd9f/rustws_async/src/main.rs#L5
https://github.com/deepu105/concurrency-benchmarks/blob/39b7d5cd3ab7b105b293cf07420c7eb94dcccd9f/rustws_async/src/main.rs#L39

It **may** be better to use [async_std::fs::read_to_string](https://docs.rs/async-std/latest/async_std/fs/fn.read_to_string.html) instead.

**Comment by deepu105** [comment]
Thanks i'll try it and see if it makes a difference

**Comment by deepu105** [comment]
I tried it and here is the result for 10 runs

```
Avg Time Taken: 20.066272727272725
Avg Requests Per Sec: 498.3481818181818
Avg Time Per Req: 200.6631818181818
Avg Time Per Req Across: 2.0067272727272725
Avg TransferRate: 137.72545454545454
```

Its not a noticeable difference but definitely helps

**Comment by deepu105** [comment]
But there is definitely an improvement and now the async version is the best performer hence I updated that code. thanks
