### ISSUE TITLE
Measure memory usage too

### ISSUE THREAD

**Issue by kokizzu** [deepu105/concurrency-benchmarks#4]
I see in the article that memory usage not measured
https://deepu.tech/concurrency-in-modern-languages-final/

```shell
alias time
time='/usr/bin/time -f "\nCPU: %Us\tReal: %es\tRAM: %MKB"'
```

**Comment by deepu105** [comment]
Thanks, I'm working on an update and will do this for that

**Comment by deepu105** [comment]
done
